derek_site/urls.py
"""This file Copyright (C) Derek Riemer, 2016
	This file is part of my personal website.

	my personal website is free software: you can redistribute it and/or modify
	it under the terms of the GNU Affero General Public License as published by
	the Free Software Foundation, either version 3 of the License, or
	(at your option) any later version.

	The code of my personal website is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with my personal website.  If not, see <http://www.gnu.org/licenses/>."""
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.http import HttpResponse
from derek_site import views
urlpatterns = patterns('',
    url(r'^weather/', include('get_weather.urls', namespace='weather')),
    url(r'^personal/', include('personal.urls', namespace='personal')),
    url(r'^admin/', include(admin.site.urls)),
)
print views
handler404 = 'derek_site.views.error404'

get_weather/urls.py
"""This file Copyright (C) Derek Riemer, 2016
	This file is part of my personal website.

	my personal website is free software: you can redistribute it and/or modify
	it under the terms of the GNU Affero General Public License as published by
	the Free Software Foundation, either version 3 of the License, or
	(at your option) any later version.

	The code of my personal website is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with my personal website.  If not, see <http://www.gnu.org/licenses/>."""
from django.conf.urls import patterns, url

from get_weather import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='home'),
    url(r'^daily/?$', views.daily, name='daily'),
    url(r'^forecast/?$', views.forecast, name='forecast'),
    url(r'^hourly/?$', views.hourly, name='hourly'),
    
)

personal/urls.py
"""This file Copyright (C) Derek Riemer, 2016
	This file is part of my personal website.

	my personal website is free software: you can redistribute it and/or modify
	it under the terms of the GNU Affero General Public License as published by
	the Free Software Foundation, either version 3 of the License, or
	(at your option) any later version.

	The code of my personal website is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with my personal website.  If not, see <http://www.gnu.org/licenses/>."""
from django.conf.urls import patterns, url

from personal import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='home'),
    url(r'^bio/?$', views.bio, name='bio'),
    url(r'^contact/?$', views.contact, name='contact'),
    url(r'^thanks/?$', views.thanks, name='thanks'),
)

weather_sim/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.http import HttpResponse
urlpatterns = patterns('',
    url(r'^weather/', include('get_weather.urls', namespace='weather')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^flocking$', lambda request: HttpResponse(open("./flocking/flocking-all.js", "rb").read(), content_type="text/plain")), #return an http response with the flocking file.
)
#handler404 = 'get_weather.views.error404'

get_weather/models.py
"""This file Copyright (C) Derek Riemer, 2016
	This file is part of my personal website.

	my personal website is free software: you can redistribute it and/or modify
	it under the terms of the GNU Affero General Public License as published by
	the Free Software Foundation, either version 3 of the License, or
	(at your option) any later version.

	The code of my personal website is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with my personal website.  If not, see <http://www.gnu.org/licenses/>."""
from django.db import models

# Create your models here.
class ApiKey(models.Model):
    name=models.CharField(max_length=20)
    api_key=models.CharField(max_length=2048)
    
    def __str__(self):
        return self.name

derek_site/views.py
"""This file Copyright (C) Derek Riemer, 2016
	This file is part of my personal website.

	my personal website is free software: you can redistribute it and/or modify
	it under the terms of the GNU Affero General Public License as published by
	the Free Software Foundation, either version 3 of the License, or
	(at your option) any later version.

	The code of my personal website is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with my personal website.  If not, see <http://www.gnu.org/licenses/>."""
from django.shortcuts import render

def getContext():
    return {
        "MENU_FILE" : "derek_site/menu.htm"
    }

def error404(request):
    return render(request, 'derek_site/404.html', getContext())

get_weather/views.py
"""This file Copyright (C) Derek Riemer, 2016
	This file is part of my personal website.

	my personal website is free software: you can redistribute it and/or modify
	it under the terms of the GNU Affero General Public License as published by
	the Free Software Foundation, either version 3 of the License, or
	(at your option) any later version.

	The code of my personal website is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with my personal website.  If not, see <http://www.gnu.org/licenses/>."""
from django.shortcuts import get_object_or_404, render
import datetime
import forecastio
from django.http import Http404
import os

API_KEY= open(os.path.join(os.path.dirname(__file__), 'apikey').replace('\\','/')).read(100)            
#helper functions.

def makeIds():
    a=1
    while True:
        b=(yield a) #allow for it to be changed.
        if b is not None:
            a=b-1 #generate b again for whatever reason.
        a+=1

def pre(id):
    return u"<span id=\"{}\"><script>var d=new Date(".format(id)

def post(id):
    return u"); document.getElementById(\""+id+"\").innerHTML=friendlyHourNames(d.getHours());</script></span>"

def getJavascriptTagForSeconds(dt, id):
    """Converts a datetime into a javascript blob that coerces into the local time reading standard when run.
    """
    return pre(id)+str(int((dt - datetime.datetime(1970, 1, 1)).total_seconds())*1000)+post(id)

def getJavascriptTag(dt, id):
    """Converts a time into a javascript blob that coerces into the local time reading standard when run.
    """
    return pre(id)+str(dt*1000)+post(id)

class Forecast:
    cashe=None
    #helper functions.

    def isCasheValid(self):
        if Forecast.cashe is not None:
            td=datetime.datetime.now()-Forecast.cashe.time
            if td.total_seconds() < 300:
                return True
            return False
        else:
            return False

    def loadForecast(self, request):
        if self.isCasheValid():
            return Forecast.cashe
        else:
            #print "Expunging weather cashe"
            try:
                lat=request.POST['lat']
                lng = request.POST['lng']
            except KeyError:
                raise Http404("bad request")
            forecast = forecastio.load_forecast(API_KEY, lat, lng)
            
            #Forecast.cashe=forecast
            #Forecast.cashe.time=datetime.datetime.now()
            unit = forecast.json.get("flags")["units"]
            if unit.lower() == 'us':
                self.tm = "F"
                self.windUnits = "MPH"
            elif unit.lower() == 'si':
                self.tm = "C"
                self.windUnits = "M/S"
            elif unit.lower() == "ca":
                self.tm = "C"
                self.windUnits = "Km/H"
            elif unit.lower() == "uk2":
                self.tm = "C"
                self.windUnits = "MPH"
            else:
                print "Units are as follows.", units
                self.tm, self.windUnits = "Error", "Error"
        return forecast



    def windy(self, speed):
        if speed <= 10:
            return "calm"
        elif speed > 10 and speed <= 15:
            return "breezy"
        elif speed > 15 and speed <= 20:
            return "quite breezy"
        elif speed > 20 and speed <= 30:
            return "windy"
        elif speed > 30 and speed <= 40:
            return "quite windy"
        elif speed > 40 and speed <= 75:
            return "extremely windy"
        else:
            return "a hurricane forced wind."

#views.

def getContext():
    return {
        "MENU_FILE" : "get_weather/menu.htm"
    }



def forecast(request):
    if request.method=="POST":
        try:
            page     = request.POST["page"]
        except KeyError:
            return Http404("Not a valid page.")
        if page=="home":
            return index(request, True)
        elif page=="hourly":
            return hourly(request, True)
        elif page=="daily":
            print "hog"
            return daily(request, True)
        else:
            return Http404("error, bad post request!")

def hourly(request, data=False):
    context=getContext()
    if data==True:
        idNum=makeIds()
        weather=Forecast()
        forecast=weather.loadForecast(request)
        tempUnits = weather.tm
        hourly=forecast.hourly()
        hourData = []
        for i in hourly.data[:24]:
            id="\"hourly_"+str(next(idNum))+'"'
            hourData.append({
                "id" : id,
                "tag": "<span id="+id+"></span>",
                "script": str(i.time*1000),
                "temp": i.temperature,
                "precip": (i.precipProbability*100)
            })
        context['forecasted'] = hourData
        context['tempUnits'] = tempUnits
        return render(request, 'get_weather/hourly_forecast.htpartial', context)
    else:
        return render(request, 'get_weather/hourly.htm', context)


def index(request, data=False): #data will make sure that this gets location or checks for the cashe first.
    #print(data)
    context=getContext()
    if data==True:
        curLst = []
        weather=Forecast()
        forecast = weather.loadForecast(request)
        tm = weather.tm
        current=forecast.currently()
        curLst .append(u"It is currently {0} and {1}&#xb0; {2}".format(current.summary, int(current.temperature), tm))
        day=forecast.daily()
        today=day.data[0]
        curLst.append(u"Today: {0}".format(today.summary))
        if today.precipProbability != 0:
            curLst.append(u"there is a {0:.0%} chance of precipitation.".format(today.precipProbability))
        else:
            curLst.append(u"No precipitation expected today.")
        
        highTime= getJavascriptTag(today.temperatureMaxTime, "high_1")
        curLst.append(u"daily high {0}&#xb0; {1} at {2}".format(today.temperatureMax, tm, highTime))
        lowTime=getJavascriptTag(today.temperatureMinTime, "low_1")
        curLst.append(u"daily low {0}&#xb0;{1} at {2}".format(today.temperatureMin, tm, lowTime))
        curLst.append(u"It is {0}, the wind speed is {1} {2}".format(weather.windy(today.windSpeed), today.windSpeed, weather.windUnits))
        context['curLst'] = curLst
        return render(request, 'get_weather/current_forecast.htpartial', context)
    else:
        return render(request, 'get_weather/index.htm', context)

def daily(request, data=False):
    context=getContext()
    idNum=makeIds()
    if data==True:
        weather = Forecast()
        forecast=weather.loadForecast(request)
        tm=weather.tm
        daily = forecast.daily()
        W_DAYS = ['Monday', 'Tuesday', 'Wednesday','Thursday', 'Friday', 'Saturday', 'Sunday']
        forecasted=[]
        for i in daily.data:
            formatter=[]
            try:
                formatter.append(W_DAYS[datetime.datetime.fromtimestamp(i.time).weekday()])
                formatter.append(i.summary)
                a=str(next(idNum))
                temperatureMaxTime = getJavascriptTag(i.temperatureMaxTime, "maxt_"+a)
                temperatureMinTime = getJavascriptTag(i.temperatureMinTime, "mint_"+str(a))
                formatter.append(u"high temperature: {0}&#xb0;{1} at {2}".format(i.temperatureMax, tm, temperatureMaxTime))
                formatter.append(u"low temperature: {0}&#xb0;{1} at {2}".format(i.temperatureMin, tm, temperatureMinTime))
                precip=""
                if i.precipProbability > 0:
                    precip+="chance of "+i.precipType
                    precip+="{:.0%}".format(i.precipProbability)
                else:
                    precip+='No precipitation is expected '
                formatter.append(precip)
                formatter.append("It will be {0}: with a wind speed of approximately {1} {2}.".format(weather.windy(i.windSpeed), i.windSpeed, weather.windUnits))
                print "foo"
                forecasted.append(formatter)
            except  NameError as e:
                forecasted.append("error retreiving current days wether.")
                print e.message
        context['forecasted']= forecasted
        print "context"
        return render(request, 'get_weather/daily_forecast.htpartial', context)
    else:
        return render(request, 'get_weather/daily.htm', context)


derek_site/templates/get_weather/audio.htm
{% comment %}
	This file Copyright (C) Derek Riemer, 2016

	This file is part of my personal website.

	my personal website is free software: you can redistribute it and/or modify
	it under the terms of the GNU Affero General Public License as published by
	the Free Software Foundation, either version 3 of the License, or
	(at your option) any later version.

	The code of my personal website is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with my personal website.  If not, see <http://www.gnu.org/licenses/>.
{% endcomment %}
<html>
    <head>
        <script src="/static/flocking-min.js"></script>
        <title> Weather for Boulder Co sonifyed.</title>
    </head>
    <body>
    <p id="h" aria-live="polite"></p>
    <script>
        var ct = [
            {% for i in hourly.data %}
                {{ i.temperature}}
                {% if hourly.data|length|add:-1 != i %}
                    ,
                {% endif %}
            {% endfor %}
        ];
        {% verbatim %}
        var synth = flock.synth({
            synthDef:{
                ugen : "flock.ugen.sin",
                freq : {
                    ugen:"flock.ugen.value",
                    value:300,
                    add:{
                        ugen:"flock.ugen.sequence",
                        freq:1,
                        list:ct,
                        mul:5
                        }
                    }
            }
        });
        var enviro = flock.init();
        synth.play();
        
        var index=0;
        setInterval(function(){
            if(index==ct.length){
                synth.pause();
                document.getElementById("h").innerHTML="done";
                clearInterval();
            }
            document.getElementById("h").innerHTML=""+ct[index++];
        },1000);
        {% endverbatim %}
        
    </script>
    
    </body>
</html>

derek_site/templates/get_weather/base.htm
{% extends "derek_site/base.htm" %}
{% comment %}
	This file Copyright (C) Derek Riemer, 2016
	This file is part of my personal website.

	my personal website is free software: you can redistribute it and/or modify
	it under the terms of the GNU Affero General Public License as published by
	the Free Software Foundation, either version 3 of the License, or
	(at your option) any later version.

	The code of my personal website is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with my personal website.  If not, see <http://www.gnu.org/licenses/>.
{% endcomment %}


{% block other %}
<script src="/static/jquery-ui.js"></script>
<script src="/static/utils.js"> </script>
<script src="/static/location.js"></script>
<script>
var page="{% block page %}  {% endblock %}";
</script>

{% csrf_token %}
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCwgZ0Ea-HQk2Q6gYcjAMHG68HSzz-F0pQ"> </script>
<script src="/static/geocoder.js"></script>

{% endblock %}
{% block dialogs %}
<div id="addressdialog" title="Current location" class="ui-dialog">
<h1 tabindex="0">Current Address.</h1>
<p tabindex="0"> Your current address is <span id="address"></span></p>
</div>
<div id="mapdialog" title="map">
<div id="map">
</div>
</div>

<script>
    $(function(){
    $( "#addressdialog" ).dialog({
        modal:true,
        autoOpen:false,
        buttons:[
            {
                text: "Show this location on a google map" ,
                click: function(){
                $("#addressdialog").dialog("close");
                geocode.loadMap();
                $("#mapdialog").dialog("open");
                }
            }
        ]
    });
    $("#mapdialog").dialog({
    modal:true,
        autoOpen:false,
                close: function(event,ui){
            $("#map").html("");
        },
        });
    });
</script>
{% endblock %}
{% block main %}
<div aria-live="polite."> Loading weather... Please wait.</div>
{% endblock %}


{% block footer %}
<div id="statusbar" class="sr_specific" role="status"></div>
Weather data provided by <a href="http://forecast.io/"> the Forecastio api.</a>
{% endblock %}

derek_site/templates/get_weather/daily.htm
{% extends "get_weather/base.htm" %}
{% comment %}
	This file Copyright (C) Derek Riemer, 2016
	This file is part of my personal website.

	my personal website is free software: you can redistribute it and/or modify
	it under the terms of the GNU Affero General Public License as published by
	the Free Software Foundation, either version 3 of the License, or
	(at your option) any later version.

	The code of my personal website is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with my personal website.  If not, see <http://www.gnu.org/licenses/>.
{% endcomment %}

{% block page %}daily{% endblock %}
{% block title %} Daily forecast. {% endblock %}
{% block header %}Daily forecast.{% endblock %}


derek_site/templates/get_weather/hourly.htm
{% extends "get_weather/base.htm" %}
{% comment %}
	This file Copyright (C) Derek Riemer, 2016
	This file is part of my personal website.

	my personal website is free software: you can redistribute it and/or modify
	it under the terms of the GNU Affero General Public License as published by
	the Free Software Foundation, either version 3 of the License, or
	(at your option) any later version.

	The code of my personal website is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with my personal website.  If not, see <http://www.gnu.org/licenses/>.
{% endcomment %}

{% block page %}hourly{% endblock %}
{% block title %} Hourly forecast. {% endblock %}
{% block other-2 %}
<script src="/static/hourly_table.js"></script>
{% endblock %}
{% block header %}Hourly forecast{% endblock %}

derek_site/templates/get_weather/index.htm
{% extends "get_weather/base.htm" %}
{% comment %}
	This file Copyright (C) Derek Riemer, 2016
	This file is part of my personal website.

	my personal website is free software: you can redistribute it and/or modify
	it under the terms of the GNU Affero General Public License as published by
	the Free Software Foundation, either version 3 of the License, or
	(at your option) any later version.

	The code of my personal website is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with my personal website.  If not, see <http://www.gnu.org/licenses/>.
{% endcomment %}
{% block page %}home{% endblock %}
{% block title %} Home {% endblock %}
{% block header %}Home{% endblock %}

derek_site/templates/get_weather/menu.htm
{% comment %}
	This file Copyright (C) Derek Riemer, 2016
	This file is part of my personal website.

	my personal website is free software: you can redistribute it and/or modify
	it under the terms of the GNU Affero General Public License as published by
	the Free Software Foundation, either version 3 of the License, or
	(at your option) any later version.

	The code of my personal website is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with my personal website.  If not, see <http://www.gnu.org/licenses/>.
{% endcomment %}
<navclass="navbar navbar-inverse">
<div class="container-fluid" role="navigation"> 
      <ul class="nav navbar-nav">
<li> <a href="#skip"> Skip to Main Content</a> </li>
<li> <a href="{% url 'weather:home' %}">Home</a> </li>
<li > <a href="{% url 'weather:daily' %}"> Daily Forecast</a> </li>
<li> <a href="{% url 'weather:hourly' %}">Hourly Forecast</a> </li>
</ul>
</div>
</nav>