derek_site/urls.py
"""This file Copyright (C) Derek Riemer, 2016
	This file is part of my personal website.

	my personal website is free software: you can redistribute it and/or modify
	it under the terms of the GNU Affero General Public License as published by
	the Free Software Foundation, either version 3 of the License, or
	(at your option) any later version.

	The code of my personal website is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with my personal website.  If not, see <http://www.gnu.org/licenses/>."""
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.http import HttpResponse
from derek_site import views
urlpatterns = patterns('',
    url(r'^weather/', include('get_weather.urls', namespace='weather')),
    url(r'^personal/', include('personal.urls', namespace='personal')),
    url(r'^admin/', include(admin.site.urls)),
)
print views
handler404 = 'derek_site.views.error404'

personal/urls.py
"""This file Copyright (C) Derek Riemer, 2016
	This file is part of my personal website.

	my personal website is free software: you can redistribute it and/or modify
	it under the terms of the GNU Affero General Public License as published by
	the Free Software Foundation, either version 3 of the License, or
	(at your option) any later version.

	The code of my personal website is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with my personal website.  If not, see <http://www.gnu.org/licenses/>."""
from django.conf.urls import patterns, url

from personal import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='home'),
    url(r'^bio/?$', views.bio, name='bio'),
    url(r'^contact/?$', views.contact, name='contact'),
    url(r'^thanks/?$', views.thanks, name='thanks'),
)

weather_sim/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.http import HttpResponse
urlpatterns = patterns('',
    url(r'^weather/', include('get_weather.urls', namespace='weather')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^flocking$', lambda request: HttpResponse(open("./flocking/flocking-all.js", "rb").read(), content_type="text/plain")), #return an http response with the flocking file.
)
#handler404 = 'get_weather.views.error404'

personal/models.py
"""This file Copyright (C) Derek Riemer, 2016
	This file is part of my personal website.

	my personal website is free software: you can redistribute it and/or modify
	it under the terms of the GNU Affero General Public License as published by
	the Free Software Foundation, either version 3 of the License, or
	(at your option) any later version.

	The code of my personal website is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with my personal website.  If not, see <http://www.gnu.org/licenses/>."""
from django.db import models

# Create your models here.
class Software_list(models.Model):
    name=models.CharField(max_length=20)
    description = models.TextField()
    source_code_download =models.URLField(blank=True)
    
    def truncated_discription(self):
        index=50
        length = len(self.description)
        while index < length:
            if self.description[index] != ' ':
                index+=1
            else:
                break
        st=self.description[:index]
        if index < len(self.description):
            st+="..."
        return st
    
    def get_latest_version(self):
        versions=sorted(list(self.version_set.all()))
        return versions[-1]
    get_latest_version.short_description= "Latest version:"
    
    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name ="software"
        verbose_name_plural = "pieces of software"

class Version(models.Model):
    software=models.ForeignKey('Software_list')
    date_released=models.DateField()
    major_version_number = models.PositiveIntegerField()
    minor_version_number = models.PositiveIntegerField()
    sub_version_number = models.PositiveIntegerField()
    stable_release = models.BooleanField(default=True)
    download=models.URLField()
    
    def __str__(self):
        return "{major}.{minor}.{sub_version}{stable}".format(
            major = self.major_version_number,
            minor = self.minor_version_number,
            sub_version = self.sub_version_number,
            stable = "" if self.stable_release else ".dev"
        )
    
    def __lt__(self,other):
        a=self.major_version_number 
        a_other = other.major_version_number
        b=self.minor_version_number
        b_other = other.minor_version_number
        c=self.sub_version_number 
        c_other = other.sub_version_number
        if a < a_other:
            return True
        elif a > a_other:
            return False
        if b < b_other:
            return True
        elif b > b_other:
            return False
        if c < c_other:
            return True
        elif c > c_other:
            return False
        #Well, they are the same version number, but checking to see if one is stable while the other is dev.
        if self.stable_release < other.stable_release:
            return True
        return False



personal/forms.py
"""This file Copyright (C) Derek Riemer, 2016
	This file is part of my personal website.

	my personal website is free software: you can redistribute it and/or modify
	it under the terms of the GNU Affero General Public License as published by
	the Free Software Foundation, either version 3 of the License, or
	(at your option) any later version.

	The code of my personal website is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with my personal website.  If not, see <http://www.gnu.org/licenses/>.
	Note that this code was modifyed off of the code on https://docs.djangoproject.com/en/1.8/topics/forms/
	"""
from django import forms
from django.core.exceptions import ValidationError
#helper functions.

def obfiscate(value):
    """ Obfiscates a given string by replacing it with the html numeric values of each of the characters. This helps to midagate some spam bots probably, but it isn't perfect, and not as good as a captcha. An example of this is like replacing space with &#32;
    """
    return "".join(["&#"+str(int(ord(i)))+";" for i in value])

def validate_checked(value):
    if value != False:
        raise ValidationError("Please uncheck the box.")

class ContactForm(forms.Form):
    your_name = forms.CharField(max_length=60)
    sender = forms.EmailField(label="Your email")
    subject = forms.CharField(max_length=60)
    message = forms.CharField(widget=forms.Textarea)
    copy_myself = forms.BooleanField(required=False, initial=True, )
    i_am_a_robot = forms.BooleanField(validators=[validate_checked], required=False, label="Read the instructions about robots.", help_text=obfiscate("I hereby declare myself a member of the human species, and I am not a computer designed for the purpose of spamming innocent humans. I promise that my intentions are without evil, and that I am not a robot, spam bot, or any other form of of non-human life that wishes to spam legitiment human intentions. As a human, I prowdly will uncheck this box. I understand that if I fail to uncheck the box above, the email will simply not go through."), initial=True) #That will help to ensure that humans are the only thing submitting the form.

derek_site/views.py
"""This file Copyright (C) Derek Riemer, 2016
	This file is part of my personal website.

	my personal website is free software: you can redistribute it and/or modify
	it under the terms of the GNU Affero General Public License as published by
	the Free Software Foundation, either version 3 of the License, or
	(at your option) any later version.

	The code of my personal website is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with my personal website.  If not, see <http://www.gnu.org/licenses/>."""
from django.shortcuts import render

def getContext():
    return {
        "MENU_FILE" : "derek_site/menu.htm"
    }

def error404(request):
    return render(request, 'derek_site/404.html', getContext())

personal/views.py
"""This file Copyright (C) Derek Riemer, 2016
	This file is part of my personal website.

	my personal website is free software: you can redistribute it and/or modify
	it under the terms of the GNU Affero General Public License as published by
	the Free Software Foundation, either version 3 of the License, or
	(at your option) any later version.

	The code of my personal website is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with my personal website.  If not, see <http://www.gnu.org/licenses/>."""
from django.shortcuts import render
from django.http import Http404, HttpResponseRedirect
from django.core.mail import EmailMessage
from .forms import *
from django.conf import settings
TO = settings.EMAIL_ADDRESS_TO
#helper functions.
def getContext():
    return {
        "MENU_FILE" : "personal/menu.htm"
    }

#views
def index(request):
    context=getContext()
    return render(request, 'personal/index.htm', context)

def bio(request):
    context=getContext()
    return render(request, 'personal/bio.htm', context)

def contact(request):
    context=getContext()
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = ContactForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            message = EmailMessage()
            message.subject = "[{} via website]".format(form.cleaned_data["your_name"])+form.cleaned_data["subject"]
            message.reply_to = [form.cleaned_data["sender"]]
            message.to=[TO]
            message.body = form.cleaned_data["message"]
            if form.cleaned_data["copy_myself"]:
                message.cc=[form.cleaned_data["sender"]]
            message.send()
            return HttpResponseRedirect('/personal/thanks/')
        else:
        
            context.update({'form': form, "errors": True})
            return render(request, 'personal/contact.htm', context)
    # if a GET (or any other method) we'll create a blank form
    else:
        form = ContactForm()
        context.update({'form': form})
    return render(request, 'personal/contact.htm', context)

def thanks(request):
    context=getContext()
    return render(request, 'personal/thanks.htm', context)

def software(request):
    context=getContext()
    apps = Software.objects.all()
    context['apps'] = apps
    return render(request, 'personal/software.htm', context)

derek_site/templates/personal/achievments.htm
{% extends "personal/base.htm" %}
{% comment %}
	This file Copyright (C) Derek Riemer, 2016
	This file is part of my personal website.

	my personal website is free software: you can redistribute it and/or modify
	it under the terms of the GNU Affero General Public License as published by
	the Free Software Foundation, either version 3 of the License, or
	(at your option) any later version.

	The code of my personal website is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with my personal website.  If not, see <http://www.gnu.org/licenses/>.
{% endcomment %}

{% block title %}Achievments and awards.{% endblock %}
{% block header %} Derek Riemer.{% endblock %}
{% block main %}


{% endblock %}

derek_site/templates/personal/base.htm
{% extends "derek_site/base.htm" %}
{% comment %}
	This file Copyright (C) Derek Riemer, 2016
	This file is part of my personal website.

	my personal website is free software: you can redistribute it and/or modify
	it under the terms of the GNU Affero General Public License as published by
	the Free Software Foundation, either version 3 of the License, or
	(at your option) any later version.

	The code of my personal website is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with my personal website.  If not, see <http://www.gnu.org/licenses/>.
{% endcomment %}


{% block footer %}

{% endblock %}

derek_site/templates/personal/bio.htm
{% extends "personal/base.htm" %}
{% comment %}
	This file Copyright (C) Derek Riemer, 2016
	This file is part of my personal website.

	my personal website is free software: you can redistribute it and/or modify
	it under the terms of the GNU Affero General Public License as published by
	the Free Software Foundation, either version 3 of the License, or
	(at your option) any later version.

	The code of my personal website is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with my personal website.  If not, see <http://www.gnu.org/licenses/>.
{% endcomment %}

{% block title %}Derek Riemer Biography{% endblock %}
{% block header %} Derek Riemer.{% endblock %}
{% block main %}
<p>
Hi, I am Derek Riemer.
I was born blind due to an eye deformity (I really don't have any sort of diagnosis, it was just a chance event with a less than 100,000 odds of happening to any random individual). 
I grew up in beautiful Arvada Colorado, with my older sister Alicia, mom Stacy and dad Scott, and many other family members close by. 
My family is verry active in the outdoors. At the age of 3, my family taught me how to ski, and it was history from there. 
I attended Anchor center for Blind Children (a preschool for the blind) until the age of 5. 
In grade school, I joined the Cub Scouts, and continued with that through out school. 
I participated in Judo, a Japanese  marshal art, for several years, where I learned many valuable lessons. I also learned about self defense and self respect there, which are both lessons that I feel all people should learn.
I joined band in 5th grade, which helped me appreciate classical music. Band was an integral  part of my development and self-confidence.
In high school, I joined the Ralston Valley high school marching band, and marched for my entire high school career. The marching band made state all 4 years, and I have performed in marching band at many highschool stadiums including the csu football stadium, and the Airforce academy stadium. <a href="#band_performances"> Click here to find links of marching band shows I participated in.</a>
I also participated in restling for 1 year of high school.
Throughout my childhood, I attended many boy scout camps, the most noteworthy of which included:
<ul>
<li> Big Horn leadership Trainin,</li>
<li> A canoe trip to the Boundery Waters of Minisota.</li>
<li> A week long backpacking trip in the Windy Peaks wilderness of Colorado.</li>
<li> Several summer camps and other camps.</li>
</ul>
In boy scouts I camped over 90 nights, and held leadership positions Including: Assistant Senior Patrol Leader, Order of the Arrow representative, Patrol leader, and Assistant Patrol Leader.
One of my greatest achievments in life was obtaining the rank of eagle scout, which included completing a project with over 300 hours of labor. My project was to extend a Gazebo at Anchor Center for Blind Children so that it included sensory rich, and unique play equipment for blind children to play on. This project was especially rewarding for me because I attended Anchor Center for Blind Children in preschool. Anchor Center is a preschool for blind children that serves children until they join kindergarden. They teach blind children techniques to use throughout their life, like pouring liquids, finding things around them, and a lot more. The preschool has helped many children for over 30 years. Anchor center also helps parents learn techniques to teach a child with little or no vision how to do things in a sight oriented world.
I am a 3rd year undergraduate student at the University of Colorado at Boulder, majoring in a B.S. of Computer Science.
My hobbies include: Skiing, bicycling, rock climbing, computer programming, playing music, writing poetry, and much more. 
I have volunteered for organizations including Anchor Center for Blind Children, the NVDA project, and the Council for Inclusion, Leadership, and Advocassy. 
I have participated in research projects at university of Colorado Boulder.
Notable research includes,
<ul>
<li>
TheTactile book project. <br/> This project aimed to use 3d printing to produce tactile books for blind children, to see if we could lower the cost of producing images for blind children. We produced a version of Goodnight Moon, and a version of <a href="https://en.wikipedia.org/wiki/Harold_and_the_Purple_Crayon">Harold and the Purple Crayon</a>
</li>
<li> 
UIST 2014 Student Inovation Conference. <br/> Me and 2 other students attended the Student inovation conference at the ACM UIST (user interface, software, and technology) conference in Hawaii. We presented an application we developed for the <a href="http://kinoma.com/create/about/">Kinoma Create</a>, which used light sensors to detect whether a light was left on in any room in a house. While this was a crude prototype, it could be marketed towards blind people who wished to know if a sighted person left a light on anywhere in a house. Other applications include a network administrator diagnosing a router problem by querying the light sensor to see if an LED light is turned on. Really, anywhere where lights are on, and someone would like to know if that light is still on could use this technology to remotely check the status of the lights.
</li>
<li>
PHET simulations for blind or visually impaired people. <br/> I worked with Professor Clayton Lewis and a team of researchers to design sound based simulations to complement the phet simulations for physics. The <a href="https://phet.colorado.edu/">Phet</a> Simulations are an innovative way of teaching science to people, and allowing people to experiment with science in a way that doesn't exist with plain paper diagrams. Unfortunately, most of these simulations are visual in nature. The work I did with Clayton, helped establish a way for making simulations be accessible to people with visual impairments. 
</li>
</ul>
I also enjoy writing random pieces of software, usually to help me solve problems. 
You can find my pieces of software on the Software page of my main site. Notable pieces of software I have written include: <ul>
<li>a weather app, which opperates from the web, requiring nothing but a web browser. </li>
<li>a utility to generate command line based ui's driven by menus, with an emphasis on being easy for the programmer to use, and which could be easily extended to present the ui in a gui format.</li>
<li> an address book organizer, which helps remove duplicate entries from address books in table based formats.</li>
<li> A clock that chimes each fifteen minutes, and chimes out the hour, which scilently runs in the backround on the users computer.</li>
<li> A program that presents flash cards to a user and allows the user to reveal a card if need be. I use it for studying a lot.</li>
<li> an app that generates words to help the user type. It learns the users most mistyped letters  and generates a word that makes the user type there worst performing letters.</li>
<li> A game that emulates whack a mole for blind people.</li>
<li> A guessing game which uses tones to represent numbers between 1 and 100.</li>
</ul>
I am also activly working on a set of tutorials to teach  Blind people how to use Google apps. Many of the Google apps work differently than other applications, and they require knowing how to use a screen reader and web browser accurately. Therefore, I created some audio tutorials to assist in teaching screen reader users on the transition to working with cloud based web applications like google apps. I received lotts of positive feedback from users of the apps. The tutorials can be found at bit.ly/GoogleAppsTutorials. 
I have skied since age 3, and enjoy skiing a lot. I have skied every run at Winter Park Resort.
</p>

{% endblock %}

derek_site/templates/personal/contact.htm
{% extends "personal/base.htm" %}
{% comment %}
	This file Copyright (C) Derek Riemer, 2016
	This file is part of my personal website.

	my personal website is free software: you can redistribute it and/or modify
	it under the terms of the GNU Affero General Public License as published by
	the Free Software Foundation, either version 3 of the License, or
	(at your option) any later version.

	The code of my personal website is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with my personal website.  If not, see <http://www.gnu.org/licenses/>.
{% endcomment %}
{% block css %}
{% verbatim %}
ul.errorlist {
color:red;
}
{% endverbatim %}
{% endblock %}
{% block title %} Contact Me {% endblock %}
{% block header %}Contact Derek Riemer.{% endblock %}
{% block main %}

{% if errors %}
<h2 class="col-nd-1"> Errors: Please fix all errors in the list below, and try to resubmit the form. </h2></h2>
<ul class="col-nd-1">
{% for field in form %}
{% for i in field.errors %}
<li> <a href="#{{field.id_for_label}}">{{field.label}}: {{i}}</a></li>
{% empty %}

{% endfor %}

{% endfor %}
</ul>
<h2 class="col-nd-1"> Form: This is the form where one or more errors exist.</h2>
{% endif %}

<form class="col-nd-1" action="/personal/contact/" method="post">
<fieldset>

    {% csrf_token %}
    {{ form }}
    </fieldset>
    <input type="submit" value="Submit" />
</form>
{% endblock %}

derek_site/templates/personal/index.htm
{% extends "personal/base.htm" %}
{% comment %}
	This file Copyright (C) Derek Riemer, 2016
	This file is part of my personal website.

	my personal website is free software: you can redistribute it and/or modify
	it under the terms of the GNU Affero General Public License as published by
	the Free Software Foundation, either version 3 of the License, or
	(at your option) any later version.

	The code of my personal website is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with my personal website.  If not, see <http://www.gnu.org/licenses/>.
{% endcomment %}

{% block title %} Home {% endblock %}
{% block header %}Derek Riemer's Web Page.{% endblock %}
{% block main %}
<p>
Hi, I am Derek Riemer.
You are on my homepage. 
<ul>
<li> If you are interested in seeing my engineering honors portfolio or resume,  You can find it by clicking the <q> Back To derekriemer.info</q> page.</li>
<li>If you want to know more about me, click on my bio. </li>
<li>If you want to get in touch, click on my contact page. </li>
<li> If you want to know about some of my hobbies, then click on my handy dandy hobbies page.</li>
<li> If you want to see random pieces of software I have written, then go to my software page.  This page can also be found on the main homepage of derekriemer.info.</li>
<li> If you would like to see some of my poetry, then click on my poetry page. (I am the 4th worst poet in the universe, behind the Vogons, and the two extinct earthling poets). If you don't know what I am talking about, then read the Hitchhikers Guide to the Galixy. It's a fun book.</li>

<li> If you want to have a cheese burger, then go eat a cheese burger! Unfortunately I don't have a page that can make you a cheese burger quite yet. Give me a few years and maybe I can 3d print you one from my awesome website. </li>
</ul>

</p>

{% endblock %}

derek_site/templates/personal/menu.htm
<navclass="navbar navbar-inverse">
      <div class="container-fluid" role="navigation">
      <ul class="nav navbar-nav">
<li> <a href="#skip"> Skip to Main Content</a> </li>
<li> <a href="{% url 'personal:home' %}">Home</a> </li>
<li> <a href="{% url 'personal:bio' %}">My Biography</a> </li>
<li> <a href="{% url 'personal:contact' %}">Contact Me</a> </li>
</ul>
</div>
</nav>

derek_site/templates/personal/thanks.htm
{% extends "personal/base.htm" %}
{% comment %}
	This file Copyright (C) Derek Riemer, 2016
	This file is part of my personal website.

	my personal website is free software: you can redistribute it and/or modify
	it under the terms of the GNU Affero General Public License as published by
	the Free Software Foundation, either version 3 of the License, or
	(at your option) any later version.

	The code of my personal website is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with my personal website.  If not, see <http://www.gnu.org/licenses/>.
{% endcomment %}

{% block title %} Thanks For Contacting Me {% endblock %}
{% block header %}Thanks{% endblock %}
{% block main %}
<p> 
Thanks for contacting me. The message you sent was emailed to me, and I will respond to you as time allows. If you wish to return to my website, click any of the links in the menu above.
</p>
{% endblock %}